### ISSUE TITLE
PROBLEMA CON SISTEMA EN PERON

### ISSUE THREAD

**Issue by victornavelino** [victornavelino/ProyectoDos#3]
Tengo el siguiente problema que se esta repitiendo en la PERON, te paso como ejemplo el dia 11/06
Importe Final de Ticket $35966.054

Información según cierre de caja:
Ventas Efectivo $23128.232
Ventas en Ctas Ctes: $373.5
Ventas con tarjetas de Credito: $11959.56 - $198.87 (recargos) = $11760.69
Ventas a empleados (vales): $198.08
Total de ventas formas de pago según cierre $35460.52

Hay una diferencia $35966.054 (según cierre de ventas) $35460.52 (según cierre de caja) = $505.552 Diferencia
Si te fijas el último ticket en excel es el Nº43431 (te lo adjunto) por un monto de $505,58 
Al parecer el sistema no tomó la forma de pago de ese ticket, me fije en las horas para ver si había un problema con eso, pero no debería haber problema, el cierre de caja fue realizado a las 14:21 mientras que la venta fue realizada a las 13:47 y el cierre de ventas fue realizado a las 13:59
Por favor fijate y decime que puede ser
[11.06.zip](https://github.com/victornavelino/ProyectoDos/files/1126380/11.06.zip)

**Comment by victoriavera09** [comment]
María Victoria VeraIngeniera en InformáticaUniversidad Nacional de Catamarca

      De: victornavelino <notifications@github.com>
 Para: victornavelino/ProyectoDos <ProyectoDos@noreply.github.com> 
CC: Subscribed <subscribed@noreply.github.com>
 Enviado: Miércoles, 5 de julio, 2017 21:07:47
 Asunto: [victornavelino/ProyectoDos] PROBLEMA CON SISTEMA EN PERON (#3)
   
Tengo el siguiente problema que se esta repitiendo en la PERON, te paso como ejemplo el dia 11/06
Importe Final de Ticket $35966.054Información según cierre de caja:
Ventas Efectivo $23128.232
Ventas en Ctas Ctes: $373.5
Ventas con tarjetas de Credito: $11959.56 - $198.87 (recargos) = $11760.69
Ventas a empleados (vales): $198.08
Total de ventas formas de pago según cierre $35460.52Hay una diferencia $35966.054 (según cierre de ventas) $35460.52 (según cierre de caja) = $505.552 Diferencia
Si te fijas el último ticket en excel es el Nº43431 (te lo adjunto) por un monto de $505,58
Al parecer el sistema no tomó la forma de pago de ese ticket, me fije en las horas para ver si había un problema con eso, pero no debería haber problema, el cierre de caja fue realizado a las 14:21 mientras que la venta fue realizada a las 13:47 y el cierre de ventas fue realizado a las 13:59
Por favor fijate y decime que puede ser
11.06.zip—
